### ISSUE TITLE
Invisibles in selection ranges are… invisible!

### ISSUE THREAD

**Issue by mcdado** [atom/base16-tomorrow-dark-theme#28]
Invisible characters seem to have the same color of the selection, making them invisible inside selection ranges.

See in One Dark:
<img width="544" alt="screen shot 2016-08-18 at 11 17 20" src="https://cloud.githubusercontent.com/assets/898057/17768687/667cdce0-6535-11e6-897f-8ab417d4e517.png">

See in Base 16 Tomorrow Dark:
<img width="557" alt="screen shot 2016-08-18 at 11 16 28" src="https://cloud.githubusercontent.com/assets/898057/17768698/7840011e-6535-11e6-8bbd-75f3279e8626.png">

**Comment by simurai** [comment]
The guideline [suggests](https://github.com/chriskempson/base16/blob/master/styling.md) to use `base03` for "Invisibles". It would look like:

![screen shot 2016-08-24 at 8 54 48 am](https://cloud.githubusercontent.com/assets/378023/17913882/74e54f04-69d8-11e6-9e08-4740cca15520.png)

For my taste a bit too strong, but maybe we should follow the official guide?

**Comment by mcdado** [comment]
Talking out of ignorance, isn't there a class for highlighted invisibles? Couldn't that be set to a different color?

**Comment by simurai** [comment]
Yeah, we could. Just wondering if we should follow the official guideline or have the Atom version be slightly tweaked.

Because it already has been "wrong" all this time, we can keep it tweaked? Here something in between by mixing the two colors `mix(@gray, @dark-gray)`:

![screen shot 2016-08-25 at 12 44 13 pm](https://cloud.githubusercontent.com/assets/378023/17956059/ac403eb6-6ac1-11e6-9b02-3c3348308100.png)

Then it would be base17. 😉

**Comment by mcdado** [comment]
I like your solution. I think that invisible characters should actually be visible, because if they are activated in the view there is generally a reason.
